print('success to import importtest')


IMPORT_LITERAL = 'ABCDE'

DEFAULT_KEY_PREFIX = "V-DEFAULT_KEY_PREFIX"
CELERY_KEY_PREFIX = "V-CELERY_KEY_PREFIX"
WEBSOCKET_KEY_PREFIX = "V-WEBSOCKET_KEY_PREFIX"
NEWS_KEY_PREFIX = "V-NEWS_KEY_PREFIX"